"""
APTLY API — ConversationTurn ORM Model

Tracks real-time orchestration metrics, decisions, and latencies for each
turn in an adaptive interview.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Float, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.answer import Answer
    from app.models.interview import Interview
    from app.models.question import Question


class ConversationTurn(UUIDMixin, TimestampMixin, Base):
    """
    Represents an adaptive conversation turn linking an answer to the next question.
    Records the decision rationale and latencies for telemetry.
    """

    __tablename__ = "conversation_turns"

    interview_id: Mapped[UUID] = mapped_column(
        ForeignKey("interviews.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The candidate's answer that triggered this turn
    answer_id: Mapped[UUID] = mapped_column(
        ForeignKey("answers.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # The subsequent question generated by the LLM
    question_id: Mapped[UUID] = mapped_column(
        ForeignKey("questions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Decision State
    decision: Mapped[str] = mapped_column(String(50), nullable=False, default="UNKNOWN")
    follow_up_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    reason_code: Mapped[str | None] = mapped_column(String(100), nullable=True)
    difficulty: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # Provider Telemetry
    llm_provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    llm_model: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Latencies (in seconds)
    latency_stt: Mapped[float | None] = mapped_column(Float, nullable=True)
    latency_llm: Mapped[float | None] = mapped_column(Float, nullable=True)
    latency_tts_first_audio: Mapped[float | None] = mapped_column(Float, nullable=True)
    latency_total: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Relationships
    interview: Mapped[Interview] = relationship("Interview", lazy="selectin")
    answer: Mapped[Answer | None] = relationship("Answer", lazy="selectin")
    question: Mapped[Question | None] = relationship("Question", lazy="selectin")

    def __repr__(self) -> str:
        return f"<ConversationTurn id={self.id} decision={self.decision} llm={self.latency_llm}s>"
